# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/robin/Documents/GitHub/FPGA-GearBox---Group-Bertolini-Liberato/dual_stepper_motor/VIVADO FILES/project_9.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/robin/Documents/GitHub/FPGA-GearBox---Group-Bertolini-Liberato/dual_stepper_motor/VIVADO FILES/project_9.gen/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/robin/Documents/GitHub/FPGA-GearBox---Group-Bertolini-Liberato/dual_stepper_motor/VIVADO FILES/project_9.srcs/sources_1/ip/bram/bram.xci
# IP: The module: 'bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/robin/Documents/GitHub/FPGA-GearBox---Group-Bertolini-Liberato/dual_stepper_motor/VIVADO FILES/project_9.gen/sources_1/ip/bram/bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
